# Generated by Django 5.0.8 on 2024-08-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendNinja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
